In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('rf_matched.csv')
data.head()
n_data = pd.read_csv('non_whitelist_filled.csv')

In [3]:
data.head()

,shop_index,manage_shop_indicator,officialstore_indicator,preferred_shop_indicator,crossborder_indicator,shop_category,new_seller_flag,seller_centre_login_L30D,shop_sku_number,shop_follower_number,shop_L180D_order,weighted_shop_rating,rf_label,rf_probs
0,207225,0,0,0,0,1,0,2,269,1029,470,2.0,0,0.84
1,308340,0,0,0,0,9,0,2,423,1143,509,4.0,0,0.96
2,350280,0,0,0,0,1,0,11,467,1641,522,5.0,0,0.90
3,396360,0,0,0,0,5,0,1,412,5700,457,2.0,0,0.92
4,412875,0,0,0,0,20,0,1,247,1143,405,0.0,0,0.92

In [6]:
index = data['shop_index']
index = list(index)
len(index)

18038

In [21]:
df = data[['shop_index', 'rf_label']]

In [22]:
df

       shop_index  rf_label
0          207225         0
1          308340         0
2          350280         0
3          396360         0
4          412875         0
...           ...       ...
18033  1486323270         0
18034  1486340640         0
18035  1486405755         0
18036  1486451250         0
18037  1486953315         0

[18038 rows x 2 columns]

In [26]:
result = pd.merge(n_data, df, on=["shop_index"])

In [27]:
result

,Unnamed: 0,decorated_indicator,manage_shop_indicator,officialstore_indicator,preferred_shop_indicator,crossborder_indicator,shop_category,new_seller_flag,seller_centre_login_L30D,shop_sku_number,...,weighted_shop_rating,performance_date,masked_item_impression,masked_order,masked_shop_page_view,masked_shop_click_from_search,masked_campaign_tab_click,masked_other_tab_click,shop_index,rf_label
0,28,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,258.0,...,4.842105,5.0,25.0,0.0,0.0,1.421053,11.0,21.526316,311799375,0
1,29,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,258.0,...,4.947368,3.0,36.0,0.0,0.0,1.000000,11.0,14.000000,311799375,0
2,30,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,258.0,...,5.000000,8.0,121.0,0.0,0.0,1.473684,11.0,21.526316,311799375,0
3,31,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,258.0,...,4.894737,12.0,9.0,0.0,0.0,1.000000,11.0,25.578947,311799375,0
4,32,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,258.0,...,4.894737,2.0,225.0,0.0,0.0,1.000000,11.0,19.789474,311799375,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252527,364244,0.0,0.0,0.0,0.0,0.0,7.0,0.0,1.0,346.0,...,4.000000,2.0,0.0,0.0,0.0,1.000000,11.0,23.263158,422200305,0
252528,364245,0.0,0.0,0.0,0.0,0.0,7.0,0.0,1.0,346.0,...,4.000000,6.0,1.0,0.0,0.0,1.000000,11.0,23.263158,422200305,0
252529,364246,0.0,0.0,0.0,0.0,0.0,7.0,0.0,1.0,346.0,...,4.000000,5.0,4.0,0.0,0.0,1.000000,11.0,23.263158,422200305,0
252530,364247,0.0,0.0,0.0,0.0,0.0,7.0,0.0,1.0,346.0,...,4.000000,1.0,0.0,0.0,0.0,1.000000,11.0,23.263158,422200305,0
252531,364248,0.0,0.0,0.0,0.0,0.0,7.0,0.0,1.0,346.0,...,4.000000,13.0,1444.0,0.0,0.0,4.000000,11.0,20.368421,422200305,0

In [28]:
result.to_csv('match_with_label.csv')

In [10]:
unmatch = n_data[~n_data.shop_index.isin(index)]
unmatch.head()

,Unnamed: 0,decorated_indicator,manage_shop_indicator,officialstore_indicator,preferred_shop_indicator,crossborder_indicator,shop_category,new_seller_flag,seller_centre_login_L30D,shop_sku_number,...,shop_L180D_order,weighted_shop_rating,performance_date,masked_item_impression,masked_order,masked_shop_page_view,masked_shop_click_from_search,masked_campaign_tab_click,masked_other_tab_click,shop_index
0,0,0.0,0.0,0.0,0.0,0.0,20.0,0.0,1.0,3899.0,...,405.0,4.578947,5.0,0.0,0.0,0.0,1.0,11.0,61.473684,1245282165
1,1,0.0,0.0,0.0,0.0,0.0,20.0,0.0,1.0,3899.0,...,405.0,4.578947,3.0,0.0,0.0,0.0,1.0,11.0,61.473684,1245282165
2,2,0.0,0.0,0.0,0.0,0.0,20.0,0.0,1.0,3899.0,...,405.0,4.526316,8.0,4.0,0.0,0.0,1.0,11.0,61.473684,1245282165
3,3,0.0,0.0,0.0,0.0,0.0,20.0,0.0,1.0,3899.0,...,405.0,4.578947,13.0,1.0,0.0,0.0,1.0,11.0,61.473684,1245282165
4,4,0.0,0.0,0.0,0.0,0.0,20.0,0.0,1.0,3899.0,...,405.0,4.578947,9.0,1.0,0.0,0.0,1.0,11.0,61.473684,1245282165

In [11]:
len(unmatch)

111720

In [12]:
unmatch.to_csv('unmatch_shops.csv')